-- Paso A.
INSERT INTO PROVEEDOR (NUMPROV, NOMPROV, CIUDAD, ESTATUS) VALUES 
    ('S20', 'PALAZUELOS', 'VENEZUELA', 10),
    ('S18', 'CORTEZ', 'BUENOS AIRES', 20),
    ('S19', 'SINATRA', 'NUEVA YORK', 10);

-- Paso B.
UPDATE PROVEEDOR 
SET CIUDAD = 'CDMX' 
WHERE CIUDAD = 'MEXICO';

-- Paso C.
UPDATE PRODUCTO 
SET COSTO = COSTO * 1.10 
WHERE COLOR = 'AZUL';

-- Paso D.
DELETE FROM COMPRAS 
WHERE NUMPROV = 'S2';

-- Paso E.
DELETE FROM COMPRAS;