-- Script de creación para la base de datos `inventario` (MySQL).
-- DROP DATABASE IF EXISTS `inventario`;
-- CREATE DATABASE `inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `inventario`;

-- Tabla PRODUCTO.
CREATE TABLE 
    `PRODUCTO` (
        `NUMPROD` CHAR(3) NOT NULL,
        `NOMPROD` VARCHAR(30) NOT NULL,
        `PESO` DECIMAL(6, 2) DEFAULT NULL,
        `COLOR` VARCHAR(20) DEFAULT NULL,
        `COSTO` DECIMAL(10, 2) DEFAULT NULL,
        `EXISTENCIAS` SMALLINT DEFAULT 0,
        PRIMARY KEY (`NUMPROD`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- Tabla PROVEEDOR.
CREATE TABLE
    `PROVEEDOR` (
        `NUMPROV` CHAR(3) NOT NULL,
        `NOMPROV` VARCHAR(30) NOT NULL,
        `CIUDAD` VARCHAR(10) DEFAULT NULL,
        `ESTATUS` TINYINT DEFAULT 1,
        PRIMARY KEY (`NUMPROV`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- Tabla COMPRAS.
CREATE TABLE
    `COMPRAS` (
        `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `NUMPROV` CHAR(3) NOT NULL,
        `NUMPROD` CHAR(3) NOT NULL,
        `CANTIDAD` SMALLINT DEFAULT 0,
        `FECHA` DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`ID`),
        INDEX `idx_numprov` (`NUMPROV`),
        INDEX `idx_numprod` (`NUMPROD`),
        CONSTRAINT `fk_compras_proveedor` FOREIGN KEY (`NUMPROV`) REFERENCES `PROVEEDOR` (`NUMPROV`) ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT `fk_compras_producto` FOREIGN KEY (`NUMPROD`) REFERENCES `PRODUCTO` (`NUMPROD`) ON DELETE RESTRICT ON UPDATE CASCADE
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;